version: '3'

services:
  db:
    image: mysql:latest
    container_name: perfume_db
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - perfume_network

  redis:
    image: redis:latest
    container_name: perfume_redis#
    ports:
      - '6379:6379'
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "very-strong-local-redis-password!@#$!%!@#"]
    volumes:
      - redis_data:/data
    networks:
      - perfume_network

volumes:
  mysql_data:
  redis_data:

networks:
  perfume_network:
