spring:
  config:
    activate:
      on-profile: 'default'
  cache:
    type: redis
    redis:
      cache-null-values: true
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${MASTER_DB_HOST}:${MASTER_DB_PORT}/${MASTER_DB_NAME}
      username: ${MASTER_DB_USERNAME}
      password: ${MASTER_DB_PASSWORD}
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${SLAVE_DB_HOST}:${SLAVE_DB_PORT}/${SLAVE_DB_NAME}
      username: ${SLAVE_DB_USERNAME}
      password: ${SLAVE_DB_PASSWORD}

    hikari:
      maximum-pool-size: 24
      max-lifetime: 1800000
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 15000
      leak-detection-threshold: 60000
      pool-name: 'perfume-db-pool'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  batch:
    jdbc:
      initialize-schema: always
      isolation-level-for-create: default
    job:
      enabled: false
  data:
    redis:
      primary:
        host: ${P_REDIS_HOST}
        port: ${P_REDIS_PORT}
        password: ${P_REDIS_AUTH_PASSWORD}
      cache:
        host: ${C_REDIS_HOST}
        port: ${C_REDIS_PORT}
        password: ${C_REDIS_AUTH_PASSWORD}

    elasticsearch:
      repositories:
        enabled: true
    web:
      pageable:
        one-indexed-parameters: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 'test'
            client-secret: 'test'
            scope:
              - profile
              - email
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
whitelist:
  cors:
    - http://localhost:3000

jwt:
  secret-key: 'readaperfumesecretkeyhelloletsmakegoodthings'
  redirect-uri: '/'
  access-token-validity-in-seconds: 7200
  refresh-token-validity-in-seconds: 604800

encryption:
  aes:
    secret-key: 'readaperfumesecretkeyhelloletsmakegoodthings'

flyway:
  enabled: false
  validate-on-migrate: false

aws:
  s3:
    access-key: 'test'
    private-key: 'test'
    bucket: 'read-a-perfume'
    cloudFrontPath: 'test'

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: trace

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true


