spring:
  profiles:
    group:
      default: 'common'
      dev: 'common'
      prod: 'common'
    include:
      - support

---

spring:
  config:
    import:
      - application-local.yaml
      - application-dev.yaml
      - application-prod.yaml
---

spring:
  config:
    activate:
      on-profile: 'common'

  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
server:
  servlet:
    context-path: /api
